module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Stock', [
      {
        type: 'Current',
        entryDate: new Date(2017, 4, 14),
        exitDate: null,
        name: 'UOB',
        sector: 'Financial',
        country: 'SG',
        currency: 'S$',
        priceBuy: 10.5,
        priceSell: null,
        priceProfitTarget: 15.2,
        priceStopLoss: 10.1,
        quantityBuy: 500,
        quantitySell: null,
        totalDividend: 50.25,
        totalCapital: 1250.50,
        capitalReturn: null,
        createdAt: null,
        updatedAt: null,
        isDeleted: false
      },
      {
        type: 'Watchlist',
        entryDate: null,
        exitDate: null,
        name: 'ST Engineering',
        sector: 'Technology',
        country: 'SG',
        currency: 'S$',
        priceBuy: 5.67,
        priceSell: null,
        priceProfitTarget: 6.78,
        priceStopLoss: null,
        quantityBuy: 1400,
        quantitySell: null,
        totalDividend: null,
        totalCapital: null,
        capitalReturn: null,
        createdAt: null,
        updatedAt: null,
        isDeleted: false
      },
      {
        type: 'Exited',
        entryDate: new Date(2016, 7, 29),
        exitDate: new Date(2017, 6, 12),
        name: 'Razer',
        sector: 'Technology',
        country: 'HK',
        currency: 'HKD',
        priceBuy: 20.91,
        priceSell: 10.92,
        priceProfitTarget: null,
        priceStopLoss: null,
        quantityBuy: 40000,
        quantitySell: 40000,
        totalDividend: null,
        totalCapital: 50802,
        capitalReturn: -10902.04,
        createdAt: null,
        updatedAt: null,
        isDeleted: false
      },
      {
        type: 'Partial Exit',
        entryDate: new Date(2017, 0, 19),
        exitDate: new Date(2017, 1, 9),
        name: 'Kulim',
        sector: 'Consumer Discretionary',
        country: 'MY',
        currency: 'RM',
        priceBuy: 2.43,
        priceSell: 5.32,
        priceProfitTarget: 5.0,
        priceStopLoss: 1.23,
        quantityBuy: 2300,
        quantitySell: 1200,
        totalDividend: 50.32,
        totalCapital: 6000,
        capitalReturn: 3210.90,
        createdAt: null,
        updatedAt: null,
        isDeleted: false
      },
      {
        type: 'Current',
        entryDate: new Date(2017, 2, 3),
        exitDate: null,
        name: 'YZJ',
        sector: 'Energy',
        country: 'SG',
        currency: 'S$',
        priceBuy: 56.5,
        priceSell: null,
        priceProfitTarget: 78.2,
        priceStopLoss: 23.1,
        quantityBuy: 900,
        quantitySell: null,
        totalDividend: null,
        totalCapital: 67294.20,
        capitalReturn: null,
        createdAt: null,
        updatedAt: null,
        isDeleted: false
      },
      {
        type: 'Exited',
        entryDate: new Date(2017, 8, 9),
        exitDate: new Date(2018, 0, 19),
        name: 'Blumont',
        sector: 'Energy',
        country: 'SG',
        currency: 'S$',
        priceBuy: 0.209,
        priceSell: 0.309,
        priceProfitTarget: null,
        priceStopLoss: null,
        quantityBuy: 59000,
        quantitySell: 59000,
        totalDividend: null,
        totalCapital: 38042.20,
        capitalReturn: 1902.42,
        createdAt: null,
        updatedAt: null,
        isDeleted: false
      }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Stock', null, {});
  }
};
